version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup-yarn:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version

workflows:
  log:
    jobs:
      - setup-yarn
