version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup-yarn:
    docker:
      - image: circleci/node:fermium
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: Getting Node Version
          command: node --version
      - run:
          name: Getting Yarn Version
          command: yarn --version

workflows:
  log:
    jobs:
      - setup-yarn
