version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup-yarn:
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - run: echo "I AM " "$PWD"
      - run:
          name: Getting Node Version
          command: node --version
      - run:
          name: Getting Yarn Version
          command: yarn --version
      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: $CIRCLE_WORKING_DIRECTORY/
          to: 's3://lolzil.la/HAHA/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  log:
    jobs:
      - setup-yarn
