version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup-yarn:
    docker:
      - image: cimg/node:14.15.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Installing dependencies
          command: yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: echo "I AM " `pwd`
      - run:
          name: Getting Node Version
          command: node --version
      - run:
          name: Getting Yarn Version
          command: yarn --version
      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./
          to: "s3://lolzil.la/HAHA/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"


workflows:
  log:
    jobs:
      - setup-yarn
